SELECT MONTH(HH.START_DATE) AS MONTH, HH.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HH
WHERE HH.CAR_ID IN (
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY H.CAR_ID
HAVING COUNT(*) >= 5
    ) 
    AND HH.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, HH.CAR_ID
ORDER BY MONTH, HH.CAR_ID DESC