SELECT EE.ID, COALESCE(E.CHILD_COUNT, 0) AS CHILD_COUNT
FROM 
(
    SELECT IE.PARENT_ID, COUNT(IE.ID) AS CHILD_COUNT
    FROM ECOLI_DATA IE
    GROUP BY IE.PARENT_ID
) AS E
RIGHT JOIN ECOLI_DATA EE
    ON EE.ID = E.PARENT_ID
ORDER BY EE.ID;