-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B
LEFT JOIN USED_GOODS_FILE F ON F.BOARD_ID = B.BOARD_ID
WHERE B.BOARD_ID = (SELECT BOARD_ID 
 FROM USED_GOODS_BOARD
 ORDER BY VIEWS DESC
 LIMIT 1)
 ORDER BY F.FILE_ID DESC