SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER AS GENDER, COUNT(DISTINCT(O.USER_ID)) AS USERS
FROM ONLINE_SALE O
JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
        AND (U.GENDER = 0 OR U.GENDER = 1)
WHERE GENDER IS NOT NULL
# WHERE YEAR(O.SALES_DATE) = 2022 AND (MONTH(O.SALES_DATE) = 1 OR MONTH(O.SALES_DATE) = 2)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER