-- 코드를 입력하세요
SELECT H.HISTORY_ID,
CASE 
    WHEN ((DATEDIFF(H.END_DATE, H.START_DATE) + 1) BETWEEN 1 AND 6) 
        THEN TRUNCATE(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1), 0)
    WHEN ((DATEDIFF(H.END_DATE, H.START_DATE) + 1) BETWEEN 7 AND 29) 
        THEN TRUNCATE(C.DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭')) * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) / 100, 0)
    WHEN ((DATEDIFF(H.END_DATE, H.START_DATE) + 1) BETWEEN 30 AND 89) 
        THEN TRUNCATE(C.DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭')) * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) / 100, 0)
    ELSE TRUNCATE(C.DAILY_FEE * (100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭')) * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) / 100, 0)
END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE AND P.CAR_TYPE = '트럭'
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC