SELECT F.ID, FN.FISH_NAME, F.LENGTH
FROM FISH_INFO F
LEFT JOIN FISH_NAME_INFO FN
    ON FN.FISH_TYPE = F.FISH_TYPE
INNER JOIN 
    (
        SELECT F.FISH_TYPE, MAX(F.LENGTH) AS LENGTH
        FROM FISH_INFO F
        GROUP BY F.FISH_TYPE
    ) SB
    ON (SB.LENGTH = F.LENGTH
        AND SB.FISH_TYPE = F.FISH_TYPE)
ORDER BY F.ID