SELECT HG.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
INNER JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
WHERE YEAR = '2022'
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1) HG ON HG.EMP_NO = HE.EMP_NO