SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
WHERE P.HOST_ID IN (
    SELECT PP.HOST_ID FROM (
        SELECT HOST_ID, COUNT(*)
        FROM PLACES
        GROUP BY HOST_ID
        HAVING COUNT(*) > 1
        ) AS PP
    )
ORDER BY P.ID